# Generated by Django 2.0.3 on 2018-04-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20180413_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
