# Generated by Django 2.0.3 on 2018-04-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_student_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
