# Generated by Django 2.0.3 on 2018-04-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='khoa',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
