# Generated by Django 2.0.3 on 2018-04-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_student_bir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bir',
            field=models.DateTimeField(),
        ),
    ]
