# Generated by Django 2.0.3 on 2018-04-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20180414_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
