# Generated by Django 2.0.3 on 2018-04-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='score2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='score3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
