# Generated by Django 2.0.3 on 2018-04-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20180414_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score4',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
