# Generated by Django 2.0.3 on 2018-04-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_student_score4'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='idCls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='idSub',
            field=models.IntegerField(default=0),
        ),
    ]
