# Generated by Django 2.0.3 on 2018-04-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20180415_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='idCls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='idSub',
            field=models.IntegerField(default=0),
        ),
    ]
