# Generated by Django 2.0.3 on 2018-04-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20180415_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('score3', models.IntegerField()),
                ('score4', models.IntegerField()),
                ('sid', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('khoa', models.CharField(max_length=30)),
                ('bir', models.DateTimeField()),
                ('idSub', models.IntegerField(default=0)),
                ('idCls', models.IntegerField(default=0)),
            ],
        ),
    ]
