# Generated by Django 2.0.3 on 2018-04-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_student2_student3'),
    ]

    operations = [
        migrations.AddField(
            model_name='student3',
            name='cls',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
