# Generated by Django 2.0.3 on 2018-04-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_student3_cls'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cls',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student1',
            name='cls',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student2',
            name='cls',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='cls',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
