# Generated by Django 2.0.3 on 2018-04-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20180415_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subjectlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
    ]
