# Generated by Django 2.0.3 on 2018-04-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_classlist_subjectlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='bir',
        ),
    ]
