# Generated by Django 2.0.3 on 2018-04-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_teacher_bir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='score',
        ),
    ]
