# Generated by Django 2.0.3 on 2018-04-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_student_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='score1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='score2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='score3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='score4',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student1',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student1',
            name='score1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student1',
            name='score2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student1',
            name='score3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student1',
            name='score4',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student2',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student2',
            name='score1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student2',
            name='score2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student2',
            name='score3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student2',
            name='score4',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student3',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student3',
            name='score1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student3',
            name='score2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student3',
            name='score3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student3',
            name='score4',
            field=models.FloatField(),
        ),
    ]
