# Generated by Django 2.0.3 on 2018-04-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20180416_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='cls',
            field=models.CharField(choices=[('Viet Nhat A', 'Viet Nhat A'), ('Viet Nhat B', 'Viet Nhat B')], max_length=30),
        ),
    ]
