# Generated by Django 2.0.3 on 2018-04-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20180416_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='cls',
            field=models.CharField(choices=[('Việt Nhật A', 'Việt Nhật A'), ('Việt Nhật B', 'Việt Nhật B'), ('Việt Nhật C', 'Việt Nhật C'), ('Việt Nhật D', 'Việt Nhật D')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('Kĩ Thuật Phần Mềm', 'Kĩ Thuật Phần Mềm'), ('Xác Suất Thống Kê', 'Xác Suất Thống Kê'), ('Math 4', 'Math 4'), ('Toán Rời Rạc', 'Toán Rời Rạc')], max_length=30),
        ),
    ]
